// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemMonitor.Core.Data;

#nullable disable

namespace SystemMonitor.Migrations
{
    [DbContext(typeof(TelemetryContext))]
    [Migration("20251121171351_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SystemMonitor.Core.Data.TelemetryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<long>("Download")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenPorts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ram")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("Upload")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
